global:
  scrape_interval: 1m
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
scrape_configs:
  - job_name: 'nodes'
    metrics_path: /metrics    
    scrape_interval: 12s
    static_configs:
            - targets: ['localhost:5054', 'localhost:5064']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
